version: '3'

services:
  news-monitor:
    build:
      context: .
      dockerfile: news_pipeline/news_monitor/Dockerfile
    environment:
      - REDIS_HOST=redis
      - KAFKA_SERVERS=kafka:9092
    ports:
      - "3002:3002"
    depends_on:
      - redis
      - kafka
      - mongodb
    networks:
      - news_network

  news-fetcher:
    build:
      context: .
      dockerfile: news_pipeline/scrapers/Dockerfile
    environment:
      - REDIS_HOST=redis
      - KAFKA_SERVERS=kafka:9092
    depends_on:
      - redis
      - kafka
      - mongodb
    networks:
      - news_network

  news-deduper:
    build:
      context: .
      dockerfile: news_pipeline/news_deduper/Dockerfile
    environment:
      - KAFKA_SERVERS=kafka:9092
    depends_on:
      - kafka
      - mongodb
    networks:
      - news_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - news_network

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - news_network

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_LOG4J_LOGGERS: "kafka=ERROR, kafka.server=ERROR, kafka.controller=ERROR, kafka.network=ERROR"
    volumes:
      - ./kafka_data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    networks:
      - news_network
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - news_network

networks:
  news_network:
    driver: bridge
